### ISSUE TITLE
.github folder does not sync from template repository

### ISSUE THREAD

**Issue by shaunaa126** [narrowspark/template-sync-action#350]
**Is your feature request related to a problem? Please describe.**
I have an issue when I try to sync .github folder and files within it from a template repository

**Describe the solution you'd like**
I would like to sync ALL files including workflow files and such in the .github folder, or have a configurable IGNORE list. It seems that the action is ignoring any changes inside .github folder.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by shaunaa126** [comment]
@narrowspark thanks for this action as it does fill in a big hole with templates. Let me know if there is a quick workaround this.

**Comment by prisis** [comment]
Hey @shaunaa126 , the ignore list, has .git in it, this is why .github is ignored, will fix it

**Comment by prisis** [comment]
the newes alpha release has the fix in it
